spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:fopag-db;DB_CLOSE_DELAY=-1
      username: sa
      password: sa
  h2:
    #http://localhost:8080/fopag/h2-console
    database:
      name: fopag-db
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    database-plataform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
